# Resolve react_native_pods.rb with node to allow for hoisting
ENV['RCT_NEW_ARCH_ENABLED'] = '0'
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MusicRatingAppNative' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    provider_path = File.join(__dir__, 'build', 'generated', 'ios', 'RCTThirdPartyComponentsProvider.mm')
    if File.exist?(provider_path)
      provider_source = File.read(provider_path)
      provider_source.sub!(
        "  dispatch_once(&nativeComponentsToken, ^{\n    thirdPartyComponents = @{",
        "  dispatch_once(&nativeComponentsToken, ^{\n    NSMutableDictionary<NSString *, Class<RCTComponentViewProtocol>> *components = [NSMutableDictionary new];"
      )
      provider_source.gsub!(
        /^\s+@"([^"]+)": NSClassFromString\(@"([^"]+)"\), \/\/ (.+)$/,
        <<~'OBJC'.rstrip
    Class<RCTComponentViewProtocol> $1Class = NSClassFromString(@"$2");
    if ($1Class != nil) {
      components[@"$1"] = $1Class; // $3
    }
        OBJC
      )
      provider_source.sub!(
        "    };\n  });",
        "    thirdPartyComponents = [components copy];\n  });"
      )
      File.write(provider_path, provider_source)
    end
  end
end
